name: base
on: [push]
jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cat /etc/apt/sources.list | sed s/^deb/deb-src/ | sudo tee /etc/apt/sources.list.d/sources.src.list
      - run: sudo apt update
      - run: sudo apt build-dep -y linux-base
      - run: sudo apt install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu git flex

